**Numpy Functions**

1) *np.sort*

In [ ]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([76, 26, 21, 11, 14, 65, 51, 65, 93, 54, 77, 24, 96, 35, 62])

In [ ]:
np.sort(a)

array([11, 14, 21, 24, 26, 35, 51, 54, 62, 65, 65, 76, 77, 93, 96])

In [ ]:
np.sort(a)[::-1] # reversed order sorting

array([96, 93, 77, 76, 65, 65, 62, 54, 51, 35, 26, 24, 21, 14, 11])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[91,  2, 67, 14],
       [44, 80, 32,  5],
       [90, 21, 49, 32],
       [11, 76, 31,  4],
       [88, 14, 58, 63],
       [17, 92, 55, 55]])

In [ ]:
np.sort(b) # by default row wise sort

array([[ 2, 14, 67, 91],
       [ 5, 32, 44, 80],
       [21, 32, 49, 90],
       [ 4, 11, 31, 76],
       [14, 58, 63, 88],
       [17, 55, 55, 92]])

In [ ]:
np.sort(b, axis=0) # (axis=0) for column wise sorting

array([[11,  2, 31,  4],
       [17, 14, 32,  5],
       [44, 21, 49, 14],
       [88, 76, 55, 32],
       [90, 80, 58, 55],
       [91, 92, 67, 63]])

2) *np.append*

In [ ]:
print(a, '\n')
print(np.append(a,101))

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62] 

[ 76  26  21  11  14  65  51  65  93  54  77  24  96  35  62 101]


In [ ]:
print(b, '\n')
print(np.append(b,np.ones((b.shape[0],1))))
print('\n')
print(np.append(b,np.ones((b.shape[0],1)),axis=1 ))

[[91  2 67 14]
 [44 80 32  5]
 [90 21 49 32]
 [11 76 31  4]
 [88 14 58 63]
 [17 92 55 55]] 

[91.  2. 67. 14. 44. 80. 32.  5. 90. 21. 49. 32. 11. 76. 31.  4. 88. 14.
 58. 63. 17. 92. 55. 55.  1.  1.  1.  1.  1.  1.]


[[91.  2. 67. 14.  1.]
 [44. 80. 32.  5.  1.]
 [90. 21. 49. 32.  1.]
 [11. 76. 31.  4.  1.]
 [88. 14. 58. 63.  1.]
 [17. 92. 55. 55.  1.]]


3) *np.concatenate*

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(7,13).reshape(2,3)

print(c,'\n')
print(d,'\n')

[[0 1 2]
 [3 4 5]] 

[[ 7  8  9]
 [10 11 12]] 



In [ ]:
print(np.concatenate((c,d)),'\n') # by default row wise concatenating
print(np.concatenate((c,d), axis=0),'\n')
print(np.concatenate((c,d), axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]] 

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


4) *np.unique*

In [ ]:
e = np.array([1,1,2,2,3,3,4,5,5,6,6,7,8,9,9])
print(e,'\n')
print(np.unique(e))

[1 1 2 2 3 3 4 5 5 6 6 7 8 9 9] 

[1 2 3 4 5 6 7 8 9]


5) *np.expand_dims*

In [ ]:
print(a)
print(a.shape)

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62]
(15,)


In [ ]:
print(np.expand_dims(a, axis=0))
print(np.expand_dims(a, axis=0).shape,'\n')

print(np.expand_dims(a, axis=1))
print(np.expand_dims(a, axis=1).shape)


[[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62]]
(1, 15) 

[[76]
 [26]
 [21]
 [11]
 [14]
 [65]
 [51]
 [65]
 [93]
 [54]
 [77]
 [24]
 [96]
 [35]
 [62]]
(15, 1)


6) *np.where*

In [ ]:
# find all the elements index whose value is greater than 50
print(a,'\n')
np.where(a>50)

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62] 



(array([ 0,  5,  6,  7,  8,  9, 10, 12, 14]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)   # n.where(condition,True,False)

array([ 0, 26, 21, 11, 14,  0,  0,  0,  0,  0,  0, 24,  0, 35,  0])

7) *np.argmax*

In [ ]:
print(a,'\n')
print(np.argmax(a))

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62] 

12


In [ ]:
print(b,'\n')
print(np.argmax(b),'\n')
print(np.argmax(b,axis=0),'\n') # 0 --> col
print(np.argmax(b,axis=1),'\n') # 1 --> row

[[91  2 67 14]
 [44 80 32  5]
 [90 21 49 32]
 [11 76 31  4]
 [88 14 58 63]
 [17 92 55 55]] 

21 

[0 5 0 4] 

[0 1 0 1 0 1] 



8) *argmin*

In [ ]:
print(a,'\n')
print(np.argmin(a))

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62] 

3


9) *np.cumsum*

In [ ]:
print(a,'\n')
print(np.cumsum(a))

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62] 

[ 76 102 123 134 148 213 264 329 422 476 553 577 673 708 770]


In [ ]:
print(b,'\n')
print(np.argmin(b),'\n')
print(np.argmin(b,axis=0),'\n') # 0 --> col
print(np.argmin(b,axis=1),'\n') # 1 --> row

[[91  2 67 14]
 [44 80 32  5]
 [90 21 49 32]
 [11 76 31  4]
 [88 14 58 63]
 [17 92 55 55]] 

1 

[3 0 3 3] 

[1 3 1 3 1 0] 



10) *cumprod*

In [ ]:
print(a,'\n')
print(np.cumprod(a))

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62] 

[                  76                 1976                41496
               456456              6390384            415374960
          21184122960        1376967992400      128058023293200
     6915133257832800   532465260853125600 -5667577813234537216
 -9131891932938575872 -6021568399787778048 -4402359312651206656]


In [ ]:
print(b,'\n')
print(np.cumprod(b))

[[91  2 67 14]
 [44 80 32  5]
 [90 21 49 32]
 [11 76 31  4]
 [88 14 58 63]
 [17 92 55 55]] 

[                  91                  182                12194
               170716              7511504            600920320
          19229450240          96147251200        8653252608000
      181718304768000     8904196933632000   284934301876224000
  3134277320638464000 -1602596589700907008  5659737940400537600
  4192207687892598784   -20604939642339328  -288469154992750592
  1715533084130017280 -2601880142066221056 -7338474267706654720
  7389898098241175552   616025781654519808 -3012070156420513792]


11) *np.percentile*

In [ ]:
a

array([76, 26, 21, 11, 14, 65, 51, 65, 93, 54, 77, 24, 96, 35, 62])

In [ ]:
print(np.percentile(a,100)) # 100 perncentile means max element of array
print(np.percentile(a,0)) # 0 perncentile means min element of array
print(np.percentile(a,50)) # 50 perncentile means mid element of array

96.0
11.0
54.0


In [ ]:
np.median(a)

54.0

12) *np.histogram*

In [ ]:
# for frequncy count and data graph
a

array([76, 26, 21, 11, 14, 65, 51, 65, 93, 54, 77, 24, 96, 35, 62])

In [ ]:
np.histogram(a,bins=[0,25,50,75,100])

(array([4, 2, 5, 4]), array([  0,  25,  50,  75, 100]))

13) *corrcoef*

In [ ]:
# corelation dependncies on one another (-1 to 1)
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

14) *np.isin*

In [ ]:
# use to search for multiple items
a

array([76, 26, 21, 11, 14, 65, 51, 65, 93, 54, 77, 24, 96, 35, 62])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

print(np.isin(a,items),'\n')
a[np.isin(a,items)]

[False False False False False False False False False False False False
 False False False] 



array([], dtype=int64)

15) *flip*

In [ ]:
print(a)
np.flip(a)

[76 26 21 11 14 65 51 65 93 54 77 24 96 35 62]


array([62, 35, 96, 24, 77, 54, 93, 65, 51, 65, 14, 11, 21, 26, 76])

In [ ]:
print(b,'\n')
print(np.flip(b),'\n')        # colum flip than row flip both
print(np.flip(b,axis=0),'\n') # axis=0 --> column flip
print(np.flip(b,axis=1))      # axis=1 --> row flip

[[91  2 67 14]
 [44 80 32  5]
 [90 21 49 32]
 [11 76 31  4]
 [88 14 58 63]
 [17 92 55 55]] 

[[55 55 92 17]
 [63 58 14 88]
 [ 4 31 76 11]
 [32 49 21 90]
 [ 5 32 80 44]
 [14 67  2 91]] 

[[17 92 55 55]
 [88 14 58 63]
 [11 76 31  4]
 [90 21 49 32]
 [44 80 32  5]
 [91  2 67 14]] 

[[14 67  2 91]
 [ 5 32 80 44]
 [32 49 21 90]
 [ 4 31 76 11]
 [63 58 14 88]
 [55 55 92 17]]


16) *np.put*

In [ ]:
# changing values in array permenently
z = a.copy()
z

array([76, 26, 21, 11, 14, 65, 51, 65, 93, 54, 77, 24, 96, 35, 62])

In [ ]:
np.put(z,[0,5],[22,4]) # (z,index number of changing values, values for giving index for changing)
z

array([22, 26, 21, 11, 14,  4, 51, 65, 93, 54, 77, 24, 96, 35, 62])

17) *np.delete*

In [ ]:
print(z, '\n')
np.delete(z, [0,4]) # (z, index number for deleting any element)

[22 26 21 11 14  4 51 65 93 54 77 24 96 35 62] 



array([26, 21, 11,  4, 51, 65, 93, 54, 77, 24, 96, 35, 62])

18) **Set Functions**

*   np.union1D
*   np.intersect1D
*   np.setdiff1D
*   np.setxor1D
*   np.in1D

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [ ]:
print(np.union1d(m,n),'\n')
print(np.intersect1d(m,n),'\n')
print(np.setdiff1d(m,n),'\n')
print(np.setdiff1d(n,m),'\n')
print(np.setxor1d(m,n),'\n')
print(np.in1d(m,1),'\n')
print(m[np.in1d(m,1)])

[1 2 3 4 5 6 7] 

[3 4 5] 

[1 2] 

[6 7] 

[1 2 6 7] 

[ True False False False False] 

[1]


19) *np.clip*

In [ ]:
a

array([76, 26, 21, 11, 14, 65, 51, 65, 93, 54, 77, 24, 96, 35, 62])

In [ ]:
np.clip(a,a_min=25,a_max=75)
# a_min replase smallest element of array a with 25 and elements > 25 becomes 25) and (a_max relpace the largest element of array with 75 and elements > 75 becomes 75)

array([75, 26, 25, 25, 25, 65, 51, 65, 75, 54, 75, 25, 75, 35, 62])